### PR TITLE
Lvruby 83: Implement recover password

### PR DESCRIPTION
**Pull request by AlinaKovtun**
## JIRA ticket

http://ssu-jira.softserveinc.com/browse/LVRUBY-83

## Code reviewers

- [x] @kmandziy
- [x] @vikabelous 

## Summary of issue

As a user, I want to receive a password-recovery email, so that I can retrieve forgotten password

## Summary of change

Implement password recovery

## Review checklist

- [x] Rubocop doesn't raise any warnings and offenses
- [ ] New features are covered with new specs
- [ ] All specs pass

### CODE REVIEW

**Comment by vikabelous** [comment]
**Code Coverage:**
:green_heart: **100.0%** covered at **1.0** hits/line

**Comment by okohuch** [comment]
squash the commits and update PR title (by default it uses commits message in case it's the only one)

**Comment by vikabelous** [comment]
**Code Coverage:**
:green_heart: **100.0%** covered at **1.0** hits/line

**Comment by vikabelous** [comment]
**Code Coverage:**
:green_heart: **100.0%** covered at **1.0** hits/line

**Comment by vikabelous** [comment]
**Code Coverage:**
:green_heart: **100.0%** covered at **1.0** hits/line

**Pull request merged**
